export const actionTypes = {
    UPDATE_ROOM_COUNT: 'UPDATE_ROOM_COUNT',
    UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD',
    SET_STAY_DURATION: 'SET_STAY_DURATION',
    SET_ALERT: 'SET_ALERT',
    UPDATE_ROOM_PRICE: 'UPDATE_ROOM_PRICE',
    CALCULATE_TOTAL_AMOUNT : 'CALCULATE_TOTAL_AMOUNT',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    UPDATE_TOTAL_AVAILABLE_ROOMS: 'UPDATE_TOTAL_AVAILABLE_ROOMS',
};
